services:
  database:
    image: pgvector/pgvector:pg16
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./../course_service/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_CREATE_DB_COURSE_SERVICE=course_service
  app-course:
    build:
      context: ./../course_service
      dockerfile: Dockerfile
    restart: always
    container_name: course_service
    expose:
      - 2000
      - 2001
    ports:
      - "2000:2000"
      - "2001:2001"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/course_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-course:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "course_service",
      "--app-port", "2001",
      "--dapr-http-port", "2000",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../course_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-course
      - redis
    network_mode: "service:app-course"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  dbdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true